# https://taskfile.dev

version: '3'

tasks:
  dev:
    cmds:
      - go run ./cmd/bin/main.go

  clean:
    desc: clean all temp project
    cmds:
      - rm -rf ./tmp coverage.out

  lint:
    desc: go linter
    cmds:
      - $GOPATH/bin/golangci-lint run ./...

  test:
    deps: [ clean ]
    desc: code go test
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

  go:generate:
    desc: go generate all
    cmds:
      - go generate ./...

  go:schema:
    desc: create module ent schema
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent new --target {{.TARGET}} {{.SCHEMA}}

  migrate:diff:mysql:
    deps: [ go:generate ]
    desc: e.g migrate:diff:mysql -- -n add_column_article -s 'mysql://root:root1234@localhost:33067/testone'
    cmds:
      - go run ./cmd/bin/main.go migrate --dialect mysql {{.CLI_ARGS}}

  migrate:diff:sqlite:
    deps: [ go:generate ]
    desc: e.g migrate:diff:sqlite -- -n {{.TITLE}}
    cmds:
      - go run ./cmd/bin/main.go migrate {{.CLI_ARGS}}

  git:delete:tag:
    desc: git delete tag
    cmds:
      - git tag --delete {{.VERSION}}
